[package]
name = "Rustty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polling = "2.5.2"
crossbeam-channel = "0.5.6"
log = "0.4.17"